### ISSUE TITLE
TypeError: catching classes that do not inherit from BaseException is not allowed

### ISSUE THREAD

**Issue by mbilling** [singer-io/tap-woocommerce#1]
Have you seen this problem before?

Deps:
Python 3.7
Windows 10
WooCommerce 3.5.1

config.json
```
{
  "url":"https://miild.dk/",
  "consumer_key":"ck_....",
  "consumer_secret":"cs_....",
  "start_date":"2016-01-01T00:00:00"
}
```

I run 
```
C:\github\miild\tap-woocommerce>tap-woocommerce --config config.json --catalog catalog.json
```

I get:
```
(venv) C:\github\miild\tap-woocommerce>tap-woocommerce --config config.json --catalog catalog.json
INFO Starting sync. Will sync these streams: ['orders']
INFO Syncing orders
{"type": "STATE", "value": {"currently_syncing": "orders"}}
{"type": "SCHEMA", "stream": "orders", "schema": {"type": "object", "properties": {"order_id": {"type": ["null", "number"]}, "order_key": {"type": ["null", "string"]}, "status": {"type": ["null", "string"]}, "date_created": {"type": ["null", "string"], "format": "date-time"}, "date_modified": {"type": ["null", "string"], "format": "date-time"}, "discount_total": {"type": ["null", "number"]}, "shipping_total": {"type": ["null", "number"]}, "total": {"type": ["null", "number"]}, "line_items": {"type": ["null", "array"], "items": {"type": ["null", "object"], "properties": {"id": {"type": ["null", "number"]}, "name": {"type": ["null", "string"]}, "product_id": {"type": ["null", "number"]}, "variation_id": {"type": ["null", "number"]}, "quantity": {"type": ["null", "number"]}, "subtotal": {"type": ["null", "number"]}, "subtotal_tax": {"type": ["null", "number"]}, "total": {"type": ["null", "number"]}, "sku": {"type": ["null", "string"]}, "price": {"type": ["null", "number"]}}}}, "shipping_lines": {"type": ["null", "array"], "items": {"type": ["null", "object"], "properties": {"id": {"type": ["null", "number"]}, "method_title": {"type": ["null", "string"]}, "method_id": {"type": ["null", "string"]}, "total": {"type": ["null", "number"]}}}}, "coupon_lines": {"type": ["null", "array"], "items": {"type": ["null", "object"], "properties": {"id": {"type": ["null", "number"]}, "code": {"type": ["null", "string"]}, "discount": {"type": ["null", "number"]}}}}}}, "key_properties": ["order_id"]}
INFO Only syncing orders updated since 2016-01-01T00:00:00
INFO GET https://miild.dk/wp-json/wc/v2/orders?after=2016-01-01T00%3A00%3A00&orderby=date&order=asc&per_page=100&page=1
INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.14900422096252441, "tags": {"endpoint": "orders", "http_status_code": 403, "status": "failed"}}
INFO METRIC: {"type": "counter", "metric": "record_count", "value": 0, "tags": {"endpoint": "orders"}}
CRITICAL catching classes that do not inherit from BaseException is not allowed
CRITICAL catching classes that do not inherit from BaseException is not allowed
Traceback (most recent call last):
  File "c:\github\tap-facebook\venv\lib\site-packages\backoff.py", line 286, in retry
    ret = target(*args, **kwargs)
  File "c:\github\tap-facebook\venv\lib\site-packages\singer_python-5.0.15-py3.7.egg\singer\utils.py", line 62, in wrapper
    return func(*args, **kwargs)
  File "c:\github\tap-facebook\venv\lib\site-packages\tap_woocommerce-0.1.1-py3.7.egg\tap_woocommerce\__init__.py", line 127, in gen_request
    resp.raise_for_status()
  File "c:\github\tap-facebook\venv\lib\site-packages\requests-2.20.0-py3.7.egg\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://miild.dk/wp-json/wc/v2/orders?after=2016-01-01T00%3A00%3A00&orderby=date&order=asc&per_page=100&page=1
```
During handling of the above exception, another exception occurred:
```
Traceback (most recent call last):
  File "C:\github\tap-facebook\venv\Scripts\tap-woocommerce-script.py", line 11, in <module>
    load_entry_point('tap-woocommerce==0.1.1', 'console_scripts', 'tap-woocommerce')()
  File "c:\github\tap-facebook\venv\lib\site-packages\singer_python-5.0.15-py3.7.egg\singer\utils.py", line 192, in wrapped
    return fnc(*args, **kwargs)
  File "c:\github\tap-facebook\venv\lib\site-packages\tap_woocommerce-0.1.1-py3.7.egg\tap_woocommerce\__init__.py", line 256, in main
    do_sync(STATE, args.catalog)
  File "c:\github\tap-facebook\venv\lib\site-packages\tap_woocommerce-0.1.1-py3.7.egg\tap_woocommerce\__init__.py", line 213, in do_sync
    raise e
  File "c:\github\tap-facebook\venv\lib\site-packages\tap_woocommerce-0.1.1-py3.7.egg\tap_woocommerce\__init__.py", line 210, in do_sync
    STATE = stream.sync(STATE, catalog)
  File "c:\github\tap-facebook\venv\lib\site-packages\tap_woocommerce-0.1.1-py3.7.egg\tap_woocommerce\__init__.py", line 143, in sync_orders
    orders = gen_request("orders",endpoint)
  File "c:\github\tap-facebook\venv\lib\site-packages\backoff.py", line 287, in retry
    except exception as e:
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Comment by mbilling** [comment]
The problem is a missing user-agent.
WooCommerce 3.5.1 responds with a status 403 when no user-agent is supplied in the request.

**Comment by luandy64** [comment]
Thanks for opening an issue! I noticed you are running this tap in a virtual environment for `tap-facebook`. Could you rerun it in a new virtual environment?

You're right regarding the user-agent. Could you open a PR, changing the request call in `gen_request` to take a custom header? After that, we can get this released.

**Comment by nick-mccoy** [comment]
Closing this.  A PR can be opened to make the suggested changes.

**Comment by azinicus** [comment]
Hi all, I'm having this issue with this tap and haven't been able to figure out how to add my own custom headers in Python, could someone create a PR as I don't have access to do it?

**Comment by mbilling** [comment]
Hi Azin,
I haven't had time to PR what i've build and changed in my version of tap-woocommerce
But I have upgraded the tap  to API 2.0 of woocommerce
I've attached my work so you can move ahead.

[tap-woocommerce.zip](https://github.com/singer-io/tap-woocommerce/files/2914642/tap-woocommerce.zip)
